### ISSUE TITLE
__init__.py doesn't contain import keras.py

### ISSUE THREAD

**Issue by lwabish** [PhilipMay/mltb#15]
after pip install mltb,
I tried to import codes from  mltb.keras but failed.
But I found the code exists in my lib folder,did you forgot to add import keras.py into __init__.py?
__version__ shows version 0.1

**Comment by PhilipMay** [comment]
Hi @luabish 
I think this is not a bug. The problem is that you need to install tensorflow. Keras does not have it as a dependency because there is a tensorflow and tensorflow-gpu package. Can you please install tensorflow and try again?

**Comment by lwabish** [comment]
I have installed keras and tensorflow.After modifying the __init__.py (importing your package keras) it worked.

**Comment by PhilipMay** [comment]
So does this need a fix on source code side? Because you say that you modified init.py
