### ISSUE TITLE
Feature Suggestion: Transformers OMLflow Callback

### ISSUE THREAD

**Issue by twolffpiggott** [PhilipMay/mltb#52]
I've been using `OptunaMLflow ` utility, and I think a great addition could be a Transformers OMFlow callback.

This callback would enable automatic MLflow logging via your wrapper function inside the internal loop of a `trainer.train()` call, to automatically record for instance the evaluation metrics every `eval_steps`, and also to optionally record the training arguments and model config as params on MLflow.

This is especially useful for trials that do not use cross-validation, and where a single model is trained for a number of epochs, allowing the eval steps to be saved as nested runs.

This implementation would be very similar to the [Transformers MLflow callback](https://huggingface.co/transformers/main_classes/callback.html#transformers.integrations.MLflowCallback), but with some custom arguments and designed to wort with an `OptunaMLflow` trial.

The Transformers implementation is [here](https://github.com/huggingface/transformers/blob/c2e0fd5283fa29bf0d0bed1fdbc9b4206e47c1d1/src/transformers/integrations.py#L834-L917).

If you agree this could be a useful feature for `mltb`, I'm happy to submit a PR– I've already put together the code for this for my use case.

**Comment by PhilipMay** [comment]
Hey @twolffpiggott thanks for this awesome idea!

> allowing the eval steps to be saved as nested runs

I think nested steps are not the way MLflow wants you to do that. See the API of log_metric here:
https://www.mlflow.org/docs/latest/python_api/mlflow.html#mlflow.log_metric

They suggest to use `step`.

> If you agree this could be a useful feature for mltb, I'm happy to submit a PR– I've already put together the code for this for my use case.

Yes I agree. I would love a PR!
The "API" should be designed in a way that allows more packages to be integrated.

**Comment by twolffpiggott** [comment]
> I think nested steps are not the way MLflow wants you to do that

Yes, you're completely right here.

OK, great, let me put forward a baseline.

**Comment by PhilipMay** [comment]
> OK, great, let me put forward a baseline.

Awesome! Thanks...

**Comment by twolffpiggott** [comment]
Closed by #53

**Comment by PhilipMay** [comment]
Thanks for closing. 👍
