### ISSUE TITLE
Add copyright to transformers integration script

### ISSUE THREAD

**Issue by PhilipMay** [PhilipMay/mltb#54]
@twolffpiggott an you please add a copyright line to your integration script?
Will give you a template later. This is just a reminder.

https://github.com/PhilipMay/mltb/blob/master/mltb/integration/transformers.py

**Comment by PhilipMay** [comment]
This would be a good template:

```
# Copyright (c) <year> by <name>
# This software is distributed under the terms of the BSD 2-Clause License.
# For details see the LICENSE file in the root directory.
```

If the contribution was not private but in context of your company add
`, <company>` after `<name>`

**Comment by twolffpiggott** [comment]
Thanks @PhilipMay will submit a PR for this now

**Comment by PhilipMay** [comment]
Also see here:

https://github.com/PhilipMay/mltb/blob/a12a658af3a730f34e3ea8096f4a2c1c17664360/mltb/omlflow.py#L1-L3

**Comment by twolffpiggott** [comment]
As a sidenote, `OMLflowCallback` extends the `transformers` [MLflowCallback](https://github.com/huggingface/transformers/blob/640318befa1a4f2850f7cdea6fceecb47898807d/src/transformers/integrations.py#L556).

As far as I've been able to read, derivative works of an Apache license can be distributed under different license terms, as long as they are compliant with the Apache license terms. [BSD-2 appears to be compliant with the Apache terms](https://softwareengineering.stackexchange.com/questions/40561/is-bsd-license-compatible-with-apache)

**Comment by PhilipMay** [comment]
I am realy not sure when work is an derivative.

Where is the line between derivative and "just using"?
Is inheritance "just using" or derivative ? I dunno...

@twolffpiggott do you have an idea?

I mean when I save a file I use the underlying OS.
Which might be Linux or Windows, and so on...

When is the integration so tight that "using" changes to "derivative work"?

**Comment by PhilipMay** [comment]
Maybe @RoHech has an idea?

**Comment by twolffpiggott** [comment]
> I am realy not sure when work is an derivative.

I am also not sure exactly where to draw this distinction.

I would classify the `OMLflowCallback` as derivative because it does not just inherit from the `TrainerCallback`, but exposes an interface modelled directly on the `MLflowCallback`, extended to work with our class and with some added optionality.

**Comment by PhilipMay** [comment]
@twolffpiggott this is interesting: https://en.wikipedia.org/wiki/Apache_License#Licensing_conditions

> The Apache License is permissive; unlike copyleft licenses, it does not require a derivative work of the software, or modifications to the original, to be distributed using the same license.

**Comment by PhilipMay** [comment]
done
